wow_races = [
    "tauren",
    "orc",
    "troll",
    "undead",
    "human",
    "gnome",
    "dwarf",
    "nightelf",
]

name_chunks = [
    "El",
    "Eld",
    "Tir",
    "Nef",
    "Eth",
    "Ith",
    "Tal",
    "Ral",
    "Ort",
    "Thul",
    "Amn",
    "Sol",
    "Shael",
    "Dol",
    "Hel",
    "Io",
    "Lum",
    "Ko",
    "Fal",
    "Lem",
    "Pul",
    "Um",
    "Mal",
    "Ist",
    "Gul",
    "Vex",
    "Ohm",
    "Lo",
    "Sur",
    "Ber",
    "Jah",
    "Cham",
    "Zod",
]

class_dict = {
    "wow_classes": [
        {"wow_class": "mage", "races": [2, 3, 4, 5]},
        {"wow_class": "priest", "races": [2, 3, 4, 6, 7]},
        {"wow_class": "warlock", "races": [1, 2, 3, 4, 5]},
        {"wow_class": "rogue", "races": [1, 2, 3, 4, 5, 6, 7]},
        {"wow_class": "druid", "races": [0, 7]},
        {"wow_class": "shaman", "races": [0, 1, 2]},
        {"wow_class": "hunter", "races": [0, 1, 2, 6, 7]},
        {"wow_class": "warrior", "races": [0, 1, 2, 3, 4, 5, 6, 7]},
        {"wow_class": "paladin", "races": [4, 6]},
    ],
}